trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

stages:
  - stage: the-build-stage
    displayName:
    jobs:
      - job: BuildNuget
        displayName: Build Nuget packages
        variables:
          BuildConfiguration: release
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'restore'
              projects: '**/*.csproj'
              feedsToUse: 'select'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: '**/*.csproj'
              arguments: '--configuration $(BuildConfiguration)'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'pack'
              packagesToPack: '**/*.csproj'
              versioningScheme: 'byPrereleaseNumber'
              majorVersion: '1'
              minorVersion: '0'
              patchVersion: '0'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: '22536cfd-0a60-41c8-8bf1-5491449af782/60997d94-c7bf-475a-bd3d-6b0719cbf381'
          
          